name: idea
description: "Pacote de recursos do projeto IDE"
version: 0.0.1
homepage: "coocree.com/idea"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  js: ^0.6.3
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.4
  logger: ^2.0.2+1
  jose: ^0.3.4
  xxtea: ^2.1.0
  crypto: ^3.0.3
  flutter_switch: ^0.3.2
  metooltip: ^0.0.7
  popover: ^0.3.0
  super_sliver_list: ^0.4.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  hive_generator: ^2.0.0
  build_runner: null
  flutter_gen_runner: null
  intl: ^0.19.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # To add assets to your package, add an assets section, like this:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
